# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: get-risk-zone
on:
  workflow_dispatch:
  schedule:
  # runs every day 1 am.
    - cron: "0 17 * * *"

jobs:
  get-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: get_risk_zones
      run: |
        python ./main.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        branch: main
        repository: .
        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
        commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
        commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
        
        # Optional. Skip internal call to `git fetch`
        skip_fetch: true    
        
        # Optional. Skip internal call to `git checkout`
        skip_checkout: true

        # Optional. Prevents the shell from expanding filenames. 
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true

        # Optional. Create given branch name in local and remote repository.
        create_branch: true
